//
//  Tags.swift
//  PlatePix
//
//  Created by Tatyana Buinitskaya on 22.01.2025.
//

import Foundation

/// A list of default emotion tags used for categorizing or labeling food items within the app.
/// These tags are localized to support multiple languages, enhancing the app's international usability.
let defaultEmotionTags: [String] = [
    "Stress",
    "Anxiety",
    "Sadness",
    "Loneliness",
    "Longing",
    "Disappointment",
    "Anger",
    "Boredom",
    "Happiness",
    "Joy",
    "Celebration",
    "Euphoria",
    "Nervousness",
    "Insecurity",
    "Tiredness"
]

/// A list of default food tags used for categorizing or labeling food items within the app.
/// These tags are localized to support multiple languages, enhancing the app's international usability.
let defaultFoodTags: [String] = [
    "Apple",
    "Banana",
    "Orange",
    "Grapes",
    "Strawberry",
    "Blueberry",
    "Pineapple",
    "Mango",
    "Pear",
    "Peach",
    "Watermelon",
    "Avocado",
    "Carrot",
    "Potato",
    "Tomato",
    "Cucumber",
    "Lettuce",
    "Spinach",
    "Broccoli",
    "Cauliflower",
    "Zucchini",
    "Bell Pepper",
    "Mushroom",
    "Onion",
    "Garlic",
    "Peas",
    "Green Beans",
    "Corn",
    "Eggplant",
    "Celery",
    "Cabbage",
    "Radish",
    "Pumpkin",
    "Beet",
    "Asparagus",
    "Apple Juice",
    "Orange Juice",
    "Milk",
    "Cheese",
    "Butter",
    "Yogurt",
    "Egg",
    "Chicken",
    "Turkey",
    "Beef",
    "Pork",
    "Lamb",
    "Duck",
    "Goose",
    "Salmon",
    "Tuna",
    "Cod",
    "Shrimp",
    "Crab",
    "Mackerel",
    "Bread",
    "Rice",
    "Pasta",
    "Noodles",
    "Quinoa",
    "Couscous",
    "Barley",
    "Oats",
    "Flour",
    "Cereal",
    "Crackers",
    "Tortilla",
    "Croissant",
    "Muffin",
    "Pancake",
    "Waffle",
    "Honey",
    "Sugar",
    "Chocolate",
    "Cake",
    "Cookie",
    "Ice Cream",
    "Chips",
    "Popcorn",
    "Almonds",
    "Cashews",
    "Walnuts",
    "Sunflower Seeds",
    "Pumpkin Seeds",
    "Peanuts",
    "Jam",
    "Pickles",
    "Ketchup",
    "Mayonnaise",
    "Mustard",
    "Coffee",
    "Tea",
    "Crispbread",
    "Muesli",
    "Granola",
    "Patty",
    "Candy",
    "Cottage cheese",
    "Omelet",
    "Porridge",
    "Coffee with milk",
    "Tea with milk",
    "Bun",
    "Prune"
]

/// A list of default reaction tags used for categorizing or labeling food items within the app.
/// These tags are localized to support multiple languages, enhancing the app's international usability.
let defaultReactionTags: [String] = [
    "Acne",
    "Diarrhea",
    "Satisfied",
    "Feeling Light",
    "Constipation",
    "No Issues",
    "A Bit Heavy",
    "Mildly Bloated",
    "Sluggish",
    "Drowsy",
    "Thirsty",
    "Stomach Ache",
    "Nauseous",
    "Bloating",
    "Acid Reflux",
    "Too Full",
    "Allergic Reaction",
    "Food Poisoning",
    "Severe Stomach Pain",
    "Dizzy",
    "Intense Fatigue"
]
