//
//  Motivations.swift
//  PlatePix
//
//  Created by Tatyana Buinitskaya on 12.02.2025.
//

import Foundation

struct Motivations {
    static let motivations = [
        Motivation(id: 0, textKey: "Motivation0"),
        Motivation(id: 1, textKey: "Motivation1"),
        Motivation(id: 2, textKey: "Motivation2"),
        Motivation(id: 3, textKey: "Motivation3"),
        Motivation(id: 4, textKey: "Motivation4"),
        Motivation(id: 5, textKey: "Motivation5"),
        Motivation(id: 6, textKey: "Motivation6"),
        Motivation(id: 7, textKey: "Motivation7"),
        Motivation(id: 8, textKey: "Motivation8"),
        Motivation(id: 9, textKey: "Motivation9"),
        Motivation(id: 10, textKey: "Motivation10"),
        Motivation(id: 11, textKey: "Motivation11"),
        Motivation(id: 12, textKey: "Motivation12"),
        Motivation(id: 13, textKey: "Motivation13"),
        Motivation(id: 14, textKey: "Motivation14"),
        Motivation(id: 15, textKey: "Motivation15"),
        Motivation(id: 16, textKey: "Motivation16"),
        Motivation(id: 17, textKey: "Motivation17"),
        Motivation(id: 18, textKey: "Motivation18"),
        Motivation(id: 19, textKey: "Motivation19"),
        Motivation(id: 20, textKey: "Motivation20"),
        Motivation(id: 21, textKey: "Motivation21"),
        Motivation(id: 22, textKey: "Motivation22"),
        Motivation(id: 23, textKey: "Motivation23"),
        Motivation(id: 24, textKey: "Motivation24"),
        Motivation(id: 25, textKey: "Motivation25"),
        Motivation(id: 26, textKey: "Motivation26"),
        Motivation(id: 27, textKey: "Motivation27"),
        Motivation(id: 28, textKey: "Motivation28"),
        Motivation(id: 29, textKey: "Motivation29"),
        Motivation(id: 30, textKey: "Motivation30"),
        Motivation(id: 31, textKey: "Motivation31"),
        Motivation(id: 32, textKey: "Motivation32"),
        Motivation(id: 33, textKey: "Motivation33"),
        Motivation(id: 34, textKey: "Motivation34"),
        Motivation(id: 35, textKey: "Motivation35"),
        Motivation(id: 36, textKey: "Motivation36"),
        Motivation(id: 37, textKey: "Motivation37"),
        Motivation(id: 38, textKey: "Motivation38"),
        Motivation(id: 39, textKey: "Motivation39"),
        Motivation(id: 40, textKey: "Motivation40"),
        Motivation(id: 41, textKey: "Motivation41"),
        Motivation(id: 42, textKey: "Motivation42"),
        Motivation(id: 43, textKey: "Motivation43"),
        Motivation(id: 44, textKey: "Motivation44"),
        Motivation(id: 45, textKey: "Motivation45"),
        Motivation(id: 46, textKey: "Motivation46"),
        Motivation(id: 47, textKey: "Motivation47"),
        Motivation(id: 48, textKey: "Motivation48"),
        Motivation(id: 49, textKey: "Motivation49"),
        Motivation(id: 50, textKey: "Motivation50"),
        Motivation(id: 51, textKey: "Motivation51"),
        Motivation(id: 52, textKey: "Motivation52"),
        Motivation(id: 53, textKey: "Motivation53"),
        Motivation(id: 54, textKey: "Motivation54"),
        Motivation(id: 55, textKey: "Motivation55"),
        Motivation(id: 56, textKey: "Motivation56"),
        Motivation(id: 57, textKey: "Motivation57"),
        Motivation(id: 58, textKey: "Motivation58"),
        Motivation(id: 59, textKey: "Motivation59"),
        Motivation(id: 60, textKey: "Motivation60"),
        Motivation(id: 61, textKey: "Motivation61"),
        Motivation(id: 62, textKey: "Motivation62"),
        Motivation(id: 63, textKey: "Motivation63"),
        Motivation(id: 64, textKey: "Motivation64"),
        Motivation(id: 65, textKey: "Motivation65"),
        Motivation(id: 66, textKey: "Motivation66"),
        Motivation(id: 67, textKey: "Motivation67"),
        Motivation(id: 68, textKey: "Motivation68"),
        Motivation(id: 69, textKey: "Motivation69"),
        Motivation(id: 70, textKey: "Motivation70"),
        Motivation(id: 71, textKey: "Motivation71"),
        Motivation(id: 72, textKey: "Motivation72"),
        Motivation(id: 73, textKey: "Motivation73"),
        Motivation(id: 74, textKey: "Motivation74"),
        Motivation(id: 75, textKey: "Motivation75"),
        Motivation(id: 76, textKey: "Motivation76"),
        Motivation(id: 77, textKey: "Motivation77"),
        Motivation(id: 78, textKey: "Motivation78"),
        Motivation(id: 79, textKey: "Motivation79"),
        Motivation(id: 80, textKey: "Motivation80"),
        Motivation(id: 81, textKey: "Motivation81"),
        Motivation(id: 82, textKey: "Motivation82"),
        Motivation(id: 83, textKey: "Motivation83"),
        Motivation(id: 84, textKey: "Motivation84"),
        Motivation(id: 85, textKey: "Motivation85"),
        Motivation(id: 86, textKey: "Motivation86"),
        Motivation(id: 87, textKey: "Motivation87"),
        Motivation(id: 88, textKey: "Motivation88"),
        Motivation(id: 89, textKey: "Motivation89"),
        Motivation(id: 90, textKey: "Motivation90"),
        Motivation(id: 91, textKey: "Motivation91"),
        Motivation(id: 92, textKey: "Motivation92"),
        Motivation(id: 93, textKey: "Motivation93"),
        Motivation(id: 94, textKey: "Motivation94"),
        Motivation(id: 95, textKey: "Motivation95"),
        Motivation(id: 96, textKey: "Motivation96"),
        Motivation(id: 97, textKey: "Motivation97"),
        Motivation(id: 98, textKey: "Motivation98"),
        Motivation(id: 99, textKey: "Motivation99"),
        Motivation(id: 100, textKey: "Motivation100")
    ]
}
