//
//  Tags.swift
//  MyPlates
//
//  Created by Tatyana Buinitskaya on 22.01.2025.
//

import Foundation

/// A list of default emotion tags used for categorizing or labeling food items within the app.
/// These tags are localized to support multiple languages, enhancing the app's international usability.

//let defaultEmotionTags: [String] = [
//    NSLocalizedString("Stress", tableName: "DefaultEmotions", comment: "Feeling overwhelmed or under pressure"),
//    NSLocalizedString("Anxiety", tableName: "DefaultEmotions", comment: "Feeling uneasy or worried"),
//    NSLocalizedString("Sadness", tableName: "DefaultEmotions", comment: "Feeling sorrowful or down"),
//    NSLocalizedString("Loneliness", tableName: "DefaultEmotions", comment: "Feeling isolated or alone"),
//    NSLocalizedString("Longing", tableName: "DefaultEmotions", comment: "Feeling a deep desire or craving"),
//    NSLocalizedString("Disappointment", tableName: "DefaultEmotions", comment: "Feeling let down or unfulfilled"),
//    NSLocalizedString("Anger", tableName: "DefaultEmotions", comment: "Feeling upset or enraged"),
//    NSLocalizedString("Boredom", tableName: "DefaultEmotions", comment: "Feeling uninterested or disengaged"),
//    NSLocalizedString("Happiness", tableName: "DefaultEmotions", comment: "Feeling content or joyful"),
//    NSLocalizedString("Joy", tableName: "DefaultEmotions", comment: "Feeling great pleasure or delight"),
//    NSLocalizedString("Celebration", tableName: "DefaultEmotions", comment: "Feeling festive or celebratory"),
//    NSLocalizedString("Euphoria", tableName: "DefaultEmotions", comment: "Feeling intense happiness or bliss"),
//    NSLocalizedString("Nervousness", tableName: "DefaultEmotions", comment: "Feeling uneasy or apprehensive"),
//    NSLocalizedString("Insecurity", tableName: "DefaultEmotions", comment: "Feeling uncertain or vulnerable")
//]

let defaultEmotionTags: [String] = [
    "Stress",
    "Anxiety",
    "Sadness",
    "Loneliness",
    "Longing",
    "Disappointment",
    "Anger",
    "Boredom",
    "Happiness",
    "Joy",
    "Celebration",
    "Euphoria",
    "Nervousness",
    "Insecurity"
]


/// A list of default food tags used for categorizing or labeling food items within the app.
/// These tags are localized to support multiple languages, enhancing the app's international usability.
//let defaultFoodTags: [String] = [
//    NSLocalizedString("Apple", tableName: "DefaultFoodTags", comment: "A fruit"),
//    NSLocalizedString("Banana", tableName: "DefaultFoodTags", comment: "A fruit"),
//    NSLocalizedString("Orange", tableName: "DefaultFoodTags", comment: "A fruit"),
//    NSLocalizedString("Grapes", tableName: "DefaultFoodTags", comment: "A fruit"),
//    NSLocalizedString("Strawberry", tableName: "DefaultFoodTags", comment: "A fruit"),
//    NSLocalizedString("Blueberry", tableName: "DefaultFoodTags", comment: "A fruit"),
//    NSLocalizedString("Pineapple", tableName: "DefaultFoodTags", comment: "A fruit"),
//    NSLocalizedString("Mango", tableName: "DefaultFoodTags", comment: "A fruit"),
//    NSLocalizedString("Pear", tableName: "DefaultFoodTags", comment: "A fruit"),
//    NSLocalizedString("Peach", tableName: "DefaultFoodTags", comment: "A fruit"),
//    NSLocalizedString("Watermelon", tableName: "DefaultFoodTags", comment: "A fruit"),
//    NSLocalizedString("Avocado", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Carrot", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Potato", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Tomato", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Cucumber", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Lettuce", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Spinach", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Broccoli", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Cauliflower", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Zucchini", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Bell Pepper", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Mushroom", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Onion", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Garlic", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Peas", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Green Beans", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Corn", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Eggplant", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Celery", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Cabbage", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Radish", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Pumpkin", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Beet", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Asparagus", tableName: "DefaultFoodTags", comment: "A vegetable"),
//    NSLocalizedString("Apple Juice", tableName: "DefaultFoodTags", comment: "A drink"),
//    NSLocalizedString("Orange Juice", tableName: "DefaultFoodTags", comment: "A drink"),
//    NSLocalizedString("Milk", tableName: "DefaultFoodTags", comment: "A drink"),
//    NSLocalizedString("Cheese", tableName: "DefaultFoodTags", comment: "A dairy product"),
//    NSLocalizedString("Butter", tableName: "DefaultFoodTags", comment: "A dairy product"),
//    NSLocalizedString("Yogurt", tableName: "DefaultFoodTags", comment: "A dairy product"),
//    NSLocalizedString("Egg", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Chicken", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Turkey", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Beef", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Pork", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Lamb", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Duck", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Goose", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Salmon", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Tuna", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Cod", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Shrimp", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Crab", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Mackerel", tableName: "DefaultFoodTags", comment: "A protein source"),
//    NSLocalizedString("Bread", tableName: "DefaultFoodTags", comment: "A staple food"),
//    NSLocalizedString("Rice", tableName: "DefaultFoodTags", comment: "A staple food"),
//    NSLocalizedString("Pasta", tableName: "DefaultFoodTags", comment: "A staple food"),
//    NSLocalizedString("Noodles", tableName: "DefaultFoodTags", comment: "A staple food"),
//    NSLocalizedString("Quinoa", tableName: "DefaultFoodTags", comment: "A staple food"),
//    NSLocalizedString("Couscous", tableName: "DefaultFoodTags", comment: "A staple food"),
//    NSLocalizedString("Barley", tableName: "DefaultFoodTags", comment: "A staple food"),
//    NSLocalizedString("Oats", tableName: "DefaultFoodTags", comment: "A staple food"),
//    NSLocalizedString("Flour", tableName: "DefaultFoodTags", comment: "A staple food"),
//    NSLocalizedString("Cereal", tableName: "DefaultFoodTags", comment: "A staple food"),
//    NSLocalizedString("Crackers", tableName: "DefaultFoodTags", comment: "A snack food"),
//    NSLocalizedString("Tortilla", tableName: "DefaultFoodTags", comment: "A staple food"),
//    NSLocalizedString("Croissant", tableName: "DefaultFoodTags", comment: "A baked good"),
//    NSLocalizedString("Muffin", tableName: "DefaultFoodTags", comment: "A baked good"),
//    NSLocalizedString("Pancake", tableName: "DefaultFoodTags", comment: "A baked good"),
//    NSLocalizedString("Waffle", tableName: "DefaultFoodTags", comment: "A baked good"),
//    NSLocalizedString("Honey", tableName: "DefaultFoodTags", comment: "A sweetener"),
//    NSLocalizedString("Sugar", tableName: "DefaultFoodTags", comment: "A sweetener"),
//    NSLocalizedString("Chocolate", tableName: "DefaultFoodTags", comment: "A snack"),
//    NSLocalizedString("Cake", tableName: "DefaultFoodTags", comment: "A dessert"),
//    NSLocalizedString("Cookie", tableName: "DefaultFoodTags", comment: "A dessert"),
//    NSLocalizedString("Ice Cream", tableName: "DefaultFoodTags", comment: "A dessert"),
//    NSLocalizedString("Chips", tableName: "DefaultFoodTags", comment: "A snack"),
//    NSLocalizedString("Popcorn", tableName: "DefaultFoodTags", comment: "A snack"),
//    NSLocalizedString("Almonds", tableName: "DefaultFoodTags", comment: "A snack"),
//    NSLocalizedString("Cashews", tableName: "DefaultFoodTags", comment: "A snack"),
//    NSLocalizedString("Walnuts", tableName: "DefaultFoodTags", comment: "A snack"),
//    NSLocalizedString("Sunflower Seeds", tableName: "DefaultFoodTags", comment: "A snack"),
//    NSLocalizedString("Pumpkin Seeds", tableName: "DefaultFoodTags", comment: "A snack"),
//    NSLocalizedString("Peanuts", tableName: "DefaultFoodTags", comment: "A snack"),
//    NSLocalizedString("Jam", tableName: "DefaultFoodTags", comment: "A spread"),
//    NSLocalizedString("Pickles", tableName: "DefaultFoodTags", comment: "A condiment"),
//    NSLocalizedString("Ketchup", tableName: "DefaultFoodTags", comment: "A condiment"),
//    NSLocalizedString("Mayonnaise", tableName: "DefaultFoodTags", comment: "A condiment"),
//    NSLocalizedString("Mustard", tableName: "DefaultFoodTags", comment: "A condiment"),
//    NSLocalizedString("Coffee", tableName: "DefaultFoodTags", comment: "A drink"),
//    NSLocalizedString("Tea", tableName: "DefaultFoodTags", comment: "A drink")
//]

/// A list of default food tags used for categorizing or labeling food items within the app.
/// These tags are localized to support multiple languages, enhancing the app's international usability.
let defaultFoodTags: [String] = [
    "Apple",
    "Banana",
    "Orange",
    "Grapes",
    "Strawberry",
    "Blueberry",
    "Pineapple",
    "Mango",
    "Pear",
    "Peach",
    "Watermelon",
    "Avocado",
    "Carrot",
    "Potato",
    "Tomato",
    "Cucumber",
    "Lettuce",
    "Spinach",
    "Broccoli",
    "Cauliflower",
    "Zucchini",
    "Bell Pepper",
    "Mushroom",
    "Onion",
    "Garlic",
    "Peas",
    "Green Beans",
    "Corn",
    "Eggplant",
    "Celery",
    "Cabbage",
    "Radish",
    "Pumpkin",
    "Beet",
    "Asparagus",
    "Apple Juice",
    "Orange Juice",
    "Milk",
    "Cheese",
    "Butter",
    "Yogurt",
    "Egg",
    "Chicken",
    "Turkey",
    "Beef",
    "Pork",
    "Lamb",
    "Duck",
    "Goose",
    "Salmon",
    "Tuna",
    "Cod",
    "Shrimp",
    "Crab",
    "Mackerel",
    "Bread",
    "Rice",
    "Pasta",
    "Noodles",
    "Quinoa",
    "Couscous",
    "Barley",
    "Oats",
    "Flour",
    "Cereal",
    "Crackers",
    "Tortilla",
    "Croissant",
    "Muffin",
    "Pancake",
    "Waffle",
    "Honey",
    "Sugar",
    "Chocolate",
    "Cake",
    "Cookie",
    "Ice Cream",
    "Chips",
    "Popcorn",
    "Almonds",
    "Cashews",
    "Walnuts",
    "Sunflower Seeds",
    "Pumpkin Seeds",
    "Peanuts",
    "Jam",
    "Pickles",
    "Ketchup",
    "Mayonnaise",
    "Mustard",
    "Coffee",
    "Tea"
]

/// A list of default month tags used for categorizing or labeling food items within the app.
/// These tags are localized to support multiple languages, enhancing the app's international usability.
// let defaultMonthTags: [String] = [
//       NSLocalizedString("January", tableName: "DefaultMonths", comment: ""),
//       NSLocalizedString("February", tableName: "DefaultMonths", comment: ""),
//       NSLocalizedString("March", tableName: "DefaultMonths", comment: ""),
//       NSLocalizedString("April", tableName: "DefaultMonths", comment: ""),
//       NSLocalizedString("May", tableName: "DefaultMonths", comment: ""),
//       NSLocalizedString("June", tableName: "DefaultMonths", comment: ""),
//       NSLocalizedString("July", tableName: "DefaultMonths", comment: ""),
//       NSLocalizedString("August", tableName: "DefaultMonths", comment: ""),
//       NSLocalizedString("September", tableName: "DefaultMonths", comment: ""),
//       NSLocalizedString("October", tableName: "DefaultMonths", comment: ""),
//       NSLocalizedString("November", tableName: "DefaultMonths", comment: ""),
//       NSLocalizedString("December", tableName: "DefaultMonths", comment: "")
//   ]

/// A list of default month tags used for categorizing or labeling food items within the app.
/// These tags are localized to support multiple languages, enhancing the app's international usability.
let defaultMonthTags: [String] = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July", 
    "August",
    "September",
    "October",
    "November",
    "December"
]

/// A list of default reaction tags used for categorizing or labeling food items within the app.
/// These tags are localized to support multiple languages, enhancing the app's international usability.
//let defaultReactionTags: [String] = [
//    NSLocalizedString("Energized", tableName: "DefaultReactions", comment: "Feeling full of energy"),
//    NSLocalizedString("Satisfied", tableName: "DefaultReactions", comment: "Feeling content and full"),
//    NSLocalizedString("Feeling Light", tableName: "DefaultReactions", comment: "Feeling good and light"),
//    NSLocalizedString("Boosted Mood", tableName: "DefaultReactions", comment: "Feeling happier"),
//    NSLocalizedString("No Issues", tableName: "DefaultReactions", comment: "No noticeable effects"),
//    NSLocalizedString("A Bit Heavy", tableName: "DefaultReactions", comment: "Feeling slightly sluggish"),
//    NSLocalizedString("Mildly Bloated", tableName: "DefaultReactions", comment: "Slight bloating"),
//    NSLocalizedString("Sluggish", tableName: "DefaultReactions", comment: "Feeling slow and low energy"),
//    NSLocalizedString("Drowsy", tableName: "DefaultReactions", comment: "Feeling sleepy"),
//    NSLocalizedString("Thirsty", tableName: "DefaultReactions", comment: "Feeling unusually thirsty"),
//    NSLocalizedString("Stomach Ache", tableName: "DefaultReactions", comment: "Mild to moderate stomach pain"),
//    NSLocalizedString("Nauseous", tableName: "DefaultReactions", comment: "Feeling like you might vomit"),
//    NSLocalizedString("Bloating", tableName: "DefaultReactions", comment: "Uncomfortable swelling in the stomach"),
//    NSLocalizedString("Acid Reflux", tableName: "DefaultReactions", comment: "Burning sensation in the throat"),
//    NSLocalizedString("Too Full", tableName: "DefaultReactions", comment: "Feeling uncomfortably full"),
//    NSLocalizedString("Allergic Reaction", tableName: "DefaultReactions", comment: "Experiencing symptoms of an allergy"),
//    NSLocalizedString("Food Poisoning", tableName: "DefaultReactions", comment: "Severe illness"),
//    NSLocalizedString("Severe Stomach Pain", tableName: "DefaultReactions", comment: "Intense pain in the stomach"),
//    NSLocalizedString("Dizzy", tableName: "DefaultReactions", comment: "Feeling dizzy"),
//    NSLocalizedString("Intense Fatigue", tableName: "DefaultReactions", comment: "Extreme tiredness")
//]

/// A list of default reaction tags used for categorizing or labeling food items within the app.
/// These tags are localized to support multiple languages, enhancing the app's international usability.
let defaultReactionTags: [String] = [
    "Energized",
    "Satisfied",
    "Feeling Light",
    "Boosted Mood",
    "No Issues",
    "A Bit Heavy",
    "Mildly Bloated",
    "Sluggish",
    "Drowsy",
    "Thirsty",
    "Stomach Ache",
    "Nauseous",
    "Bloating",
    "Acid Reflux",
    "Too Full",
    "Allergic Reaction",
    "Food Poisoning",
    "Severe Stomach Pain",
    "Dizzy",
    "Intense Fatigue"
]


