//
//  Tags.swift
//  MyPlates
//
//  Created by Tatyana Buinitskaya on 22.01.2025.
//

import Foundation


let defaultTags: [String] = [
    "Apple",
    "Banana",
    "Orange",
    "Grapes",
    "Strawberry",
    "Blueberry",
    "Pineapple",
    "Mango",
    "Pear",
    "Peach",
    "Watermelon",
    "Cantaloupe",
    "Avocado",
    "Carrot",
    "Potato",
    "Sweet Potato",
    "Tomato",
    "Cucumber",
    "Lettuce",
    "Spinach",
    "Broccoli",
    "Cauliflower",
    "Zucchini",
    "Bell Pepper",
    "Mushroom",
    "Onion",
    "Garlic",
    "Peas",
    "Green Beans",
    "Corn",
    "Eggplant",
    "Celery",
    "Cabbage",
    "Radish",
    "Pumpkin",
    "Beet",
    "Asparagus",
    "Apple Juice",
    "Orange Juice",
    "Milk",
    "Cheese",
    "Butter",
    "Yogurt",
    "Egg",
    "Chicken",
    "Turkey",
    "Beef",
    "Pork",
    "Lamb",
    "Duck",
    "Goose",
    "Salmon",
    "Tuna",
    "Cod",
    "Shrimp",
    "Crab",
    "Lobster",
    "Mackerel",
    "Oyster",
    "Clam",
    "Bread",
    "Rice",
    "Pasta",
    "Noodles",
    "Quinoa",
    "Couscous",
    "Barley",
    "Oats",
    "Flour",
    "Cereal",
    "Crackers",
    "Tortilla",
    "Bagel",
    "Croissant",
    "Muffin",
    "Biscuit",
    "Pancake",
    "Waffle",
    "Syrup",
    "Honey",
    "Sugar",
    "Chocolate",
    "Cake",
    "Cookie",
    "Ice Cream",
    "Chips",
    "Popcorn",
    "Peanuts",
    "Almonds",
    "Cashews",
    "Walnuts",
    "Sunflower Seeds",
    "Pumpkin Seeds",
    "Peanut Butter",
    "Jam",
    "Pickles",
    "Ketchup",
    "Mayonnaise",
    "Mustard"
]
