//
//  Tags.swift
//  MyPlates
//
//  Created by Tatyana Buinitskaya on 22.01.2025.
//

import Foundation


let defaultTags: [String] = [
    NSLocalizedString("Apple", tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Banana", tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Orange", tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Grapes", tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Strawberry",tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Blueberry", tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Pineapple", tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Mango", tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Pear", tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Peach", tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Watermelon", tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Cantaloupe", tableName: "DefaultTags", comment: "A fruit"),
    NSLocalizedString("Avocado", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Carrot", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Potato", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Sweet Potato", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Tomato", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Cucumber", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Lettuce", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Spinach", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Broccoli", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Cauliflower", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Zucchini", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Bell Pepper", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Mushroom", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Onion", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Garlic", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Peas", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Green Beans", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Corn", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Eggplant", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Celery", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Cabbage", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Radish", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Pumpkin", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Beet", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Asparagus", tableName: "DefaultTags", comment: "A vegetable"),
    NSLocalizedString("Apple Juice", tableName: "DefaultTags", comment: "A drink"),
    NSLocalizedString("Orange Juice", tableName: "DefaultTags", comment: "A drink"),
    NSLocalizedString("Milk", tableName: "DefaultTags", comment: "A drink"),
    NSLocalizedString("Cheese", tableName: "DefaultTags", comment: "A dairy product"),
    NSLocalizedString("Butter", tableName: "DefaultTags", comment: "A dairy product"),
    NSLocalizedString("Yogurt", tableName: "DefaultTags", comment: "A dairy product"),
    NSLocalizedString("Egg", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Chicken", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Turkey", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Beef", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Pork", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Lamb", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Duck", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Goose", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Salmon", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Tuna", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Cod", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Shrimp",tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Crab", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Lobster", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Mackerel", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Oyster", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Clam", tableName: "DefaultTags", comment: "A protein source"),
    NSLocalizedString("Bread", tableName: "DefaultTags", comment: "A staple food"),
    NSLocalizedString("Rice", tableName: "DefaultTags", comment: "A staple food"),
    NSLocalizedString("Pasta", tableName: "DefaultTags", comment: "A staple food"),
    NSLocalizedString("Noodles", tableName: "DefaultTags", comment: "A staple food"),
    NSLocalizedString("Quinoa", tableName: "DefaultTags", comment: "A staple food"),
    NSLocalizedString("Couscous", tableName: "DefaultTags", comment: "A staple food"),
    NSLocalizedString("Barley", tableName: "DefaultTags", comment: "A staple food"),
    NSLocalizedString("Oats", tableName: "DefaultTags", comment: "A staple food"),
    NSLocalizedString("Flour", tableName: "DefaultTags", comment: "A staple food"),
    NSLocalizedString("Cereal", tableName: "DefaultTags", comment: "A staple food"),
    NSLocalizedString("Crackers", tableName: "DefaultTags", comment: "A snack food"),
    NSLocalizedString("Tortilla", tableName: "DefaultTags", comment: "A staple food"),
    NSLocalizedString("Bagel", tableName: "DefaultTags", comment: "A baked good"),
    NSLocalizedString("Croissant", tableName: "DefaultTags", comment: "A baked good"),
    NSLocalizedString("Muffin", tableName: "DefaultTags", comment: "A baked good"),
    NSLocalizedString("Biscuit", tableName: "DefaultTags", comment: "A baked good"),
    NSLocalizedString("Pancake", tableName: "DefaultTags", comment: "A baked good"),
    NSLocalizedString("Waffle", tableName: "DefaultTags", comment: "A baked good"),
    NSLocalizedString("Syrup", tableName: "DefaultTags", comment: "A sweetener"),
    NSLocalizedString("Honey", tableName: "DefaultTags", comment: "A sweetener"),
    NSLocalizedString("Sugar", tableName: "DefaultTags", comment: "A sweetener"),
    NSLocalizedString("Chocolate", tableName: "DefaultTags", comment: "A snack"),
    NSLocalizedString("Cake", tableName: "DefaultTags", comment: "A dessert"),
    NSLocalizedString("Cookie", tableName: "DefaultTags", comment: "A dessert"),
    NSLocalizedString("Ice Cream", tableName: "DefaultTags", comment: "A dessert"),
    NSLocalizedString("Chips", tableName: "DefaultTags", comment: "A snack"),
    NSLocalizedString("Popcorn", tableName: "DefaultTags", comment: "A snack"),
    NSLocalizedString("Peanuts", tableName: "DefaultTags", comment: "A snack"),
    NSLocalizedString("Almonds", tableName: "DefaultTags", comment: "A snack"),
    NSLocalizedString("Cashews", tableName: "DefaultTags", comment: "A snack"),
    NSLocalizedString("Walnuts", tableName: "DefaultTags", comment: "A snack"),
    NSLocalizedString("Sunflower Seeds", tableName: "DefaultTags", comment: "A snack"),
    NSLocalizedString("Pumpkin Seeds", tableName: "DefaultTags", comment: "A snack"),
    NSLocalizedString("Peanut Butter", tableName: "DefaultTags", comment: "A spread"),
    NSLocalizedString("Jam", tableName: "DefaultTags", comment: "A spread"),
    NSLocalizedString("Pickles", tableName: "DefaultTags", comment: "A condiment"),
    NSLocalizedString("Ketchup", tableName: "DefaultTags", comment: "A condiment"),
    NSLocalizedString("Mayonnaise", tableName: "DefaultTags", comment: "A condiment"),
    NSLocalizedString("Mustard", tableName: "DefaultTags", comment: "A condiment")
]

//let defaultTags: [String] = [
//    "Apple",
//    "Banana",
//    "Orange",
//    "Grapes",
//    "Strawberry",
//    "Blueberry",
//    "Pineapple",
//    "Mango",
//    "Pear",
//    "Peach",
//    "Watermelon",
//    "Cantaloupe",
//    "Avocado",
//    "Carrot",
//    "Potato",
//    "Sweet Potato",
//    "Tomato",
//    "Cucumber",
//    "Lettuce",
//    "Spinach",
//    "Broccoli",
//    "Cauliflower",
//    "Zucchini",
//    "Bell Pepper",
//    "Mushroom",
//    "Onion",
//    "Garlic",
//    "Peas",
//    "Green Beans",
//    "Corn",
//    "Eggplant",
//    "Celery",
//    "Cabbage",
//    "Radish",
//    "Pumpkin",
//    "Beet",
//    "Asparagus",
//    "Apple Juice",
//    "Orange Juice",
//    "Milk",
//    "Cheese",
//    "Butter",
//    "Yogurt",
//    "Egg",
//    "Chicken",
//    "Turkey",
//    "Beef",
//    "Pork",
//    "Lamb",
//    "Duck",
//    "Goose",
//    "Salmon",
//    "Tuna",
//    "Cod",
//    "Shrimp",
//    "Crab",
//    "Lobster",
//    "Mackerel",
//    "Oyster",
//    "Clam",
//    "Bread",
//    "Rice",
//    "Pasta",
//    "Noodles",
//    "Quinoa",
//    "Couscous",
//    "Barley",
//    "Oats",
//    "Flour",
//    "Cereal",
//    "Crackers",
//    "Tortilla",
//    "Bagel",
//    "Croissant",
//    "Muffin",
//    "Biscuit",
//    "Pancake",
//    "Waffle",
//    "Syrup",
//    "Honey",
//    "Sugar",
//    "Chocolate",
//    "Cake",
//    "Cookie",
//    "Ice Cream",
//    "Chips",
//    "Popcorn",
//    "Peanuts",
//    "Almonds",
//    "Cashews",
//    "Walnuts",
//    "Sunflower Seeds",
//    "Pumpkin Seeds",
//    "Peanut Butter",
//    "Jam",
//    "Pickles",
//    "Ketchup",
//    "Mayonnaise",
//    "Mustard"
//]
